version: "3"

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    # networks:
    #   - fcexperience

  db:
    image: mysql:8.0.30-debian
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=chat
    volumes:
      - .docker/dbdata:/var/lib/mysql
    # networks:
    #   - fcexperience

# networks:
#   fcexperience:
#     external: true